version: "3"

# Named volumes
volumes:
  # Mongodb Data
  boilerplate-hapijs-mongo:
    driver: local

  # Postgres Data
  boilerplate-hapijs-postgres:
    driver: local

services:
  api:
    image: ambientum/node:lts
    container_name: boilerplate-hapijs-node
    command: npm run dev
    volumes:
      - .:/var/www/app
    ports:
      - "3000:3000"
      - "5645:5645"
    links:
      - mongodb

  build:
    image: ambientum/node:lts
    container_name: boilerplate-hapijs-build
    command: npm run build-watch
    volumes:
      - .:/var/www/app

  mongodb:
    container_name: boilerplate-hapijs-mongo
    restart: on-failure
    image: bitnami/mongodb:3.6
    ports:
      - "27017:27017"
    volumes:
      - boilerplate-hapijs-mongo:/bitnami
    environment:
      - MONGODB_USERNAME=app
      - MONGODB_PASSWORD=app@mongo
      - MONGODB_DATABASE=app

  postgres:
    container_name: boilerplate-hapijs-postgres
    restart: on-failure
    image: postgres:11-alpine
    ports:
      - "15432:5432"
    volumes:
      - boilerplate-hapijs-postgres
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app@postgres
      - POSTGRES_DB=app
